# Generated by Django 5.0.4 on 2024-04-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0002_alter_address_city_alter_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='date_saved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
